services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend
    container_name: backend
    ports:
      - '${PORT}:3003'
    env_file:
      - .env
    networks:
      ION_network:
        ipv4_address: 172.20.0.3

networks:
  ION_network:
    name: ION
    driver: bridge
    external: false
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
